### ISSUE TITLE
Scope for SetThreadName.h

### ISSUE THREAD

**Issue by BMillikan** [ankurverma85/libadsb#3]
The compiler (gcc version 9.4.0) is unable to find the local file SetThreadName.h as it is using a scope for #include.  #include <SetThreadName.h> will only find this file if in the include search paths.  I had to change to #include "SetThreadName.h" to get to compile.

**Comment by ankurvdev** [comment]
[4f89fe8f752e91fffdc276b2e175946763497cde
](https://github.com/ankurvdev/libadsb/commit/4f89fe8f752e91fffdc276b2e175946763497cde)
